import BuildupService from "@/services/main/BuildupService";
export default {
  data() {
    return {
      numbers: [
        { value: "가격", label: "가격" },
        { value: "브랜드 이미지", label: "브랜드 이미지" },
        { value: "제공하는 서비스", label: "제공하는 서비스" },
        { value: "특정한 기능", label: "특정한 기능" },
        { value: "기능 수", label: "기능 수" },
        {
          value: "제품/서비스 품질 및 신뢰성",
          label: "제품/서비스 품질 및 신뢰성",
        },
        { value: "보증 및 A/S", label: "보증 및 A/S" },
        { value: "사용 편의성", label: "사용 편의성" },
        { value: "스타일과 디자인", label: "스타일과 디자인" },
        { value: "고객지원 수준", label: "고객지원 수준" },
        { value: "구매조건", label: "구매조건" },
        {
          value: "제품/서비스에 대한 접근성",
          label: "제품/서비스에 대한 접근성",
        },
        { value: "시장점유율", label: "시장점유율" },
        { value: "유통채널", label: "유통채널" },
        { value: "고객만족도(고객평가)", label: "고객만족도(고객평가)" },
        { value: "기타", label: "기타" },
      ],
      aPositiveTitle14_1: "",
      aPositiveTitle14_2: "",
      aPositiveTitle14_3: "",
      aPositiveContent14_1: "",
      aPositiveContent14_2: "",
      aPositiveContent14_3: "",
      bPositiveTitle14_1: "",
      bPositiveTitle14_2: "",
      bPositiveTitle14_3: "",
      bPositiveContent14_1: "",
      bPositiveContent14_2: "",
      bPositiveContent14_3: "",
      cPositiveTitle14_1: "",
      cPositiveTitle14_2: "",
      cPositiveTitle14_3: "",
      cPositiveContent14_1: "",
      cPositiveContent14_2: "",
      cPositiveContent14_3: "",
      aNegativeTitle14_1: "",
      aNegativeTitle14_2: "",
      aNegativeTitle14_3: "",
      aNegativeContent14_1: "",
      aNegativeContent14_2: "",
      aNegativeContent14_3: "",
      bNegativeTitle14_1: "",
      bNegativeTitle14_2: "",
      bNegativeTitle14_3: "",
      bNegativeContent14_1: "",
      bNegativeContent14_2: "",
      bNegativeContent14_3: "",
      cNegativeTitle14_1: "",
      cNegativeTitle14_2: "",
      cNegativeTitle14_3: "",
      cNegativeContent14_1: "",
      cNegativeContent14_2: "",
      cNegativeContent14_3: "",
      productA: "",
      productB: "",
      productC: "",
      memo: "",
    };
  },
  methods: {
    async saveBuildStep14() {
      if (confirm("저장하시겠습니까?")) {
        var data = {
          aPositiveTitle1: this.aPositiveTitle14_1,
          aPositiveTitle2: this.aPositiveTitle14_2,
          aPositiveTitle3: this.aPositiveTitle14_3,
          aPositiveContent1: this.aPositiveContent14_1,
          aPositiveContent2: this.aPositiveContent14_2,
          aPositiveContent3: this.aPositiveContent14_3,
          bPositiveTitle1: this.bPositiveTitle14_1,
          bPositiveTitle2: this.bPositiveTitle14_2,
          bPositiveTitle3: this.bPositiveTitle14_3,
          bPositiveContent1: this.bPositiveContent14_1,
          bPositiveContent2: this.bPositiveContent14_2,
          bPositiveContent3: this.bPositiveContent14_3,
          cPositiveTitle1: this.cPositiveTitle14_1,
          cPositiveTitle2: this.cPositiveTitle14_2,
          cPositiveTitle3: this.cPositiveTitle14_3,
          cPositiveContent1: this.cPositiveContent14_1,
          cPositiveContent2: this.cPositiveContent14_2,
          cPositiveContent3: this.cPositiveContent14_3,
          aNegativeTitle1: this.aNegativeTitle14_1,
          aNegativeTitle2: this.aNegativeTitle14_2,
          aNegativeTitle3: this.aNegativeTitle14_3,
          aNegativeContent1: this.aNegativeContent14_1,
          aNegativeContent2: this.aNegativeContent14_2,
          aNegativeContent3: this.aNegativeContent14_3,
          bNegativeTitle1: this.bNegativeTitle14_1,
          bNegativeTitle2: this.bNegativeTitle14_2,
          bNegativeTitle3: this.bNegativeTitle14_3,
          bNegativeContent1: this.bNegativeContent14_1,
          bNegativeContent2: this.bNegativeContent14_2,
          bNegativeContent3: this.bNegativeContent14_3,
          cNegativeTitle1: this.cNegativeTitle14_1,
          cNegativeTitle2: this.cNegativeTitle14_2,
          cNegativeTitle3: this.cNegativeTitle14_3,
          cNegativeContent1: this.cNegativeContent14_1,
          cNegativeContent2: this.cNegativeContent14_2,
          cNegativeContent3: this.cNegativeContent14_3,
          productA: this.productA,
          productB: this.productB,
          productC: this.productC,
          memo: this.memo,
        };
        try {
          await BuildupService.saveBuildStep14(this.$route.params.id, data);
          alert("저장되었습니다.");
          await this.getBuildStep14(this.$route.params.id);
        } catch (error) {
          // 오류 처리 로직 추가
        }
      } else {
        alert("취소되었습니다.");
      }
    },
    async getBuildStep14(id) {
      await BuildupService.getBuildStep14(id)
        .then((res) => {
          (this.aPositiveTitle14_1 = res.data.aPositiveTitle1),
            (this.aPositiveTitle14_2 = res.data.aPositiveTitle2),
            (this.aPositiveTitle14_3 = res.data.aPositiveTitle3),
            (this.aPositiveContent14_1 = res.data.aPositiveContent1),
            (this.aPositiveContent14_2 = res.data.aPositiveContent2),
            (this.aPositiveContent14_3 = res.data.aPositiveContent3),
            (this.bPositiveTitle14_1 = res.data.bPositiveTitle1),
            (this.bPositiveTitle14_2 = res.data.bPositiveTitle2),
            (this.bPositiveTitle14_3 = res.data.bPositiveTitle3),
            (this.bPositiveContent14_1 = res.data.bPositiveContent1),
            (this.bPositiveContent14_2 = res.data.bPositiveContent2),
            (this.bPositiveContent14_3 = res.data.bPositiveContent3),
            (this.cPositiveTitle14_1 = res.data.cPositiveTitle1),
            (this.cPositiveTitle14_2 = res.data.cPositiveTitle2),
            (this.cPositiveTitle14_3 = res.data.cPositiveTitle3),
            (this.cPositiveContent14_1 = res.data.cPositiveContent1),
            (this.cPositiveContent14_2 = res.data.cPositiveContent2),
            (this.cPositiveContent14_3 = res.data.cPositiveContent3),
            (this.aNegativeTitle14_1 = res.data.aNegativeTitle1),
            (this.aNegativeTitle14_2 = res.data.aNegativeTitle2),
            (this.aNegativeTitle14_3 = res.data.aNegativeTitle3),
            (this.aNegativeContent14_1 = res.data.aNegativeContent1),
            (this.aNegativeContent14_2 = res.data.aNegativeContent2),
            (this.aNegativeContent14_3 = res.data.aNegativeContent3),
            (this.bNegativeTitle14_1 = res.data.bNegativeTitle1),
            (this.bNegativeTitle14_2 = res.data.bNegativeTitle2),
            (this.bNegativeTitle14_3 = res.data.bNegativeTitle3),
            (this.bNegativeContent14_1 = res.data.bNegativeContent1),
            (this.bNegativeContent14_2 = res.data.bNegativeContent2),
            (this.bNegativeContent14_3 = res.data.bNegativeContent3),
            (this.cNegativeTitle14_1 = res.data.cNegativeTitle1),
            (this.cNegativeTitle14_2 = res.data.cNegativeTitle2),
            (this.cNegativeTitle14_3 = res.data.cNegativeTitle3),
            (this.cNegativeContent14_1 = res.data.cNegativeContent1),
            (this.cNegativeContent14_2 = res.data.cNegativeContent2),
            (this.cNegativeContent14_3 = res.data.cNegativeContent3),
            (this.productA = res.data.productA),
            (this.productB = res.data.productB),
            (this.productC = res.data.productC),
            (this.memo = res.data.memo);
        })
        .catch(() => {});
    },
  },
  async mounted() {
    await this.getBuildStep14(this.$route.params.id);
  },
  async beforeDestroy() {
    var data = {
      aPositiveTitle1: this.aPositiveTitle14_1,
      aPositiveTitle2: this.aPositiveTitle14_2,
      aPositiveTitle3: this.aPositiveTitle14_3,
      aPositiveContent1: this.aPositiveContent14_1,
      aPositiveContent2: this.aPositiveContent14_2,
      aPositiveContent3: this.aPositiveContent14_3,
      bPositiveTitle1: this.bPositiveTitle14_1,
      bPositiveTitle2: this.bPositiveTitle14_2,
      bPositiveTitle3: this.bPositiveTitle14_3,
      bPositiveContent1: this.bPositiveContent14_1,
      bPositiveContent2: this.bPositiveContent14_2,
      bPositiveContent3: this.bPositiveContent14_3,
      cPositiveTitle1: this.cPositiveTitle14_1,
      cPositiveTitle2: this.cPositiveTitle14_2,
      cPositiveTitle3: this.cPositiveTitle14_3,
      cPositiveContent1: this.cPositiveContent14_1,
      cPositiveContent2: this.cPositiveContent14_2,
      cPositiveContent3: this.cPositiveContent14_3,
      aNegativeTitle1: this.aNegativeTitle14_1,
      aNegativeTitle2: this.aNegativeTitle14_2,
      aNegativeTitle3: this.aNegativeTitle14_3,
      aNegativeContent1: this.aNegativeContent14_1,
      aNegativeContent2: this.aNegativeContent14_2,
      aNegativeContent3: this.aNegativeContent14_3,
      bNegativeTitle1: this.bNegativeTitle14_1,
      bNegativeTitle2: this.bNegativeTitle14_2,
      bNegativeTitle3: this.bNegativeTitle14_3,
      bNegativeContent1: this.bNegativeContent14_1,
      bNegativeContent2: this.bNegativeContent14_2,
      bNegativeContent3: this.bNegativeContent14_3,
      cNegativeTitle1: this.cNegativeTitle14_1,
      cNegativeTitle2: this.cNegativeTitle14_2,
      cNegativeTitle3: this.cNegativeTitle14_3,
      cNegativeContent1: this.cNegativeContent14_1,
      cNegativeContent2: this.cNegativeContent14_2,
      cNegativeContent3: this.cNegativeContent14_3,
      productA: this.productA,
      productB: this.productB,
      productC: this.productC,
      memo: this.memo,
    };
    try {
      await BuildupService.saveBuildStep14(this.$route.params.id, data);
      await this.getBuildStep14(this.$route.params.id);
    } catch (error) {
      console.log(error)  ;
    }
  },
};
